// <auto-generated />
using System;
using GasMe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GasMe.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210125001056_updateScheduleModel")]
    partial class updateScheduleModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GasMe.Data.Models.Currency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("GasMe.Data.Models.Cylinder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("currencyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("Cylinder");
                });

            modelBuilder.Entity("GasMe.Data.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("cylinderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("pickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("transactionStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("GasMe.Data.Models.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("cylinderType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("pickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("scheduleBasis")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("scheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("transactionStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
